### ISSUE TITLE
Dimension out of range (expected to be in range of [-1, 0], but got 1) 

### ISSUE THREAD

**Issue by adteamvozniak** [Arhosseini77/SUM#2]
Dear Authors, 
I am having the following issue while trying to launch the training procedure:

Also, I am having some unresolved dependencies:
torchtext 0.18.0 has requirement torch>=2.3.0, but you have torch 2.1.0+cu121.
numba 0.56.4+1.g5f1bc7084 has requirement numpy<1.24,>=1.18, but you have numpy 1.26.0.
cupy-cuda12x 12.0.0b3 has requirement numpy<1.26,>=1.20, but you have numpy 1.26.0.

Could you please suggest? Also, can you provide a list installed packages maybe since that could help to resolve the dependency issues. 

Traceback (most recent call last):
  File "/home/jovyan/Torte/SUM/SUM-main/train.py", line 151, in <module>
    outputs = model(stimuli, condition)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/Torte/SUM/SUM-main/net/models/SUM.py", line 30, in forward
    logits = self.salu_mamba(x, condition)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/Torte/SUM/SUM-main/net/models/vmamba.py", line 815, in forward
    x = self.forward_features_up(x, skip_list, condition)
  File "/home/jovyan/Torte/SUM/SUM-main/net/models/vmamba.py", line 792, in forward_features_up
    x = layer_up(x, condition)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/Torte/SUM/SUM-main/net/models/vmamba.py", line 681, in forward
    x = blk(x, condition)  # Pass the condition vector to each block
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/Torte/SUM/SUM-main/net/models/vmamba.py", line 552, in forward
    indices = torch.argmax(condition, dim=1) # previous settings
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by Arhosseini77** [comment]
Thank you for reaching out and providing detailed information about the issues you're encountering. I'm sorry to hear you're experiencing difficulties with launching the training procedure. Let me address your concerns step-by-step:

### **1. Dependency Conflicts**


To ensure compatibility, I recommend the following steps:

1. **Use Google Colab:** I've successfully run the training code on Google Colab without encountering these dependency issues. Colab provides a managed environment that often resolves such conflicts automatically.

2. **Install Dependencies Anew:** In Colab, follow the installation instructions provided in the repository to set up the environment from scratch. This approach helps in avoiding version mismatches.

3. I have also provide you mine env versions too 
[sum_env.zip](https://github.com/user-attachments/files/17410712/sum_env.zip)

### **2. Addressing the Runtime Error**

The error you encountered:
```
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```
indicates that the `condition` tensor passed to `torch.argmax` does not have the expected number of dimensions. Specifically, it seems `condition` must be a 1D tensor instead of the expected 2D tensor.

For guidance on how to properly feed data into the model, please refer to the [`test_model.py`](https://github.com/Arhosseini77/SUM/blob/7ea1c8a1b64302bd41c97b7f5ab4c05947f27d93/test_model.py#L26) script in the repository. This script provides examples and can help ensure that you're supplying the model with correctly formatted inputs.

### **4. Additional Support**

If you continue to experience issues or have further questions, please don't hesitate to reach out via email at [arhosseini77@ut.ac.ir](mailto:arhosseini77@ut.ac.ir).

**Comment by adteamvozniak** [comment]
Thanks Arhosseini77,
Yeah, by this time I resolved the issue with the dimensionality already.

For other users ==> if you are retraining on your own dataset, with a single class label, you may want to add an extra logic, including the one_hot encoding transformation.

Best Regards,
